# This rule is an exception that tells Netlify to leave the sitemap file alone.
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

# This is the main rule that handles all other pages for your app.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200